name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: checkout
        uses: actions/checkout@v4
      - name: golangci-lint
        # reference: https://golangci-lint.run/usage/configuration/#command-line-options
        timeout-minutes: 3
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56
